### ISSUE TITLE
wrong word

### ISSUE THREAD

**Issue by GurgenMelikyan** [DavidTsat/physmath_cpp_group#2]
These numbers are OR of these subsets
https://github.com/DavidTsat/physmath_cpp_group/blob/e53f59008be650543f1c86133fb1a8264c38adc3/lesson%201%20-%20fundamental%20types%20and%20bitwise%20operations/homework%203..txt#L66

**Comment by DavidTsat** [comment]
Yes, you are right. I fixed it.
